・課題1
  ・WHERE句にidとtaikaiFlagを指定することになりIndexが効かなくなる
  ・退会済みユーザに関連するコンテンツを非表示にする場合、
    都度アプリ側でテーブルを結合しtaikaiFlagを見る必要がある。(忘れそう)

・課題2
@startuml

entity user {
    id: varchar [PK]
}

entity user_detail {
    user_id: varchar [PK]
    --
    name: varchar
}

entity active_user {
    user_id: varchar [PK]
}

entity taikai_user {
    user_id: varchar [PK]
}

user ||-do-|| user_detail
user ||-do-|| active_user
user ||-do-|| taikai_user

@enduml

・課題3
  ・ブログサービスなどでユーザが記事を誤って削除してもすぐに復旧できるよう削除した時、
    物理削除せず論理削除する。

・参考
失敗から学ぶRDBの正しい歩き方 第5章 フラグの闇
https://www.slideshare.net/t_wada/ronsakucasual
