@startuml


entity "顧客マスタ" as customer {
  + 顧客ID [PK]
  --
  顧客名
  電話番号
}

entity "注文テーブル" as order {
  + 注文ID [PK]
  --
  # 顧客ID [FK]
  注文日時
  支払い済みフラグ
}

entity "注文明細テーブル" as order_detail {
  + 注文ID   [PK]
  + 明細番号 [PK]
  --
  商品ID [FK]
  セット商品ID [FK]
  個数
  さび抜きフラグ
  シャリタイプ(大, 小)
}

/'
  お好みすし
'/
entity "商品マスタ" as product {
  + 商品ID [PK]
  --
  商品名
  商品カテゴリID [FK]
  価格ID [FK]
}

/'
  商品カテゴリ
  例:お好みすし, デザート
'/
entity "商品カテゴリ" as product_category {
  + 商品カテゴリID [PK]
  --
  商品カテゴリ名
}

/'
  セットメニュー
'/
entity "セット商品マスタ" as set_product {
  + セット商品ID [PK]
  --
  セット商品名
  セット商品カテゴリID [FK]
  価格
}

/'
  セット商品のカテゴリ名
  例:盛り込み、にぎり
'/
entity "セット商品カテゴリ" as set_product_category {
  + セット商品カテゴリID [PK]
  --
  セット商品名カテゴリ名
}

/'
  セットメニューと寿司ネタを紐付ける
'/
entity "セット商品リンク" as set_product_link {
  セット商品ID [PK]
  商品ID
}

entity "価格マスタ" as price {
  + 価格ID [PK]
  --
  価格
}

/'
関係性
------   :1
----||   :1 and only 1
----o|   :0 or 1
-----{   :many
----|{   :1 or more
----o{   :0 or many

entityの位置
ri ...right
le ...left
do ...down
'/
customer       |o-ri-o{     order
order          ||-ri-|{     order_detail
order_detail   }-ri-||      product
order_detail   }-do-||      set_product
product        ||-do-o{     set_product_link
set_product    ||-ri-o{     set_product_link
product        }|-ri-||     price

@enduml

