
・分析のみの用途の場合
履歴データを同じデータベースサーバに保存せず、別サーバを立てて保存する。
アプリケーションが使うデータベースが軽量になるよう履歴データは別データベースに保存、
分析する場合はそのデータベースのデータを使う。

@startuml


entity "テキスト履歴" as text_histories {
  + テキストID [PK]
  + 連番 [PK]
  --
  過去テキスト内容
  日時
}

/'
関係性
------   :1
----||   :1 and only 1
----o|   :0 or 1
-----{   :many
----|{   :1 or more
----o{   :0 or many

entityの位置
ri ...right
le ...left
do ...down
'/

@enduml

