version: '3'
services:
  database:
    image: mysql/mysql-server:latest
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./test_db-master:/test_db-master
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
