@startuml
!theme aws-orange
skinparam PackageStyle rectangle

package チームEntity {
  object チーム
  object ペア
}

package 参加者Entity {
  object 参加者
}

package 課題進捗ステータスEntity {
  object 課題進捗ステータス
}

object 参加者 {
  ID
  参加者名
  メールアドレス
  在籍ステータス
}

object 課題進捗ステータス {
  ID
  課題ID
  参加者ID
  進捗ステータス
}

object 課題 {
  ID
  タイトル
  内容
}

object ペア {
  ID
  ペア名
  参加者IDリスト
}

object チーム {
  ID
  チーム名
  ペアIDリスト
  休会中参加者IDリスト
}

note right of 参加者 {
  - メールアドレスは重複しない
  - 在籍ステータスは[在籍中, 休会中, 退会済]のいずれか
  - 在籍ステータスが"在籍中"以外の場合、チーム, ペアには所属しない
}

note right of 課題進捗ステータス {
  - 進捗ステータスは[未着手, レビュー待ち, 完了]のいずれか
  - 進捗ステータスを変えられるのは課題の所有者のみ
  - 進捗ステータスが完了のものは[未着手, レビュー待ち]に戻せない
}

note right of ペア {
  - ペア名は英字のみ, 1文字
  - 参加者リストは2~3名, 同じチームの参加者のみ
}

note left of チーム {
  - チーム名は数字のみ, 3文字以下, 重複しない
  - 参加者リストは最低3名
}


チーム "1" -right-* "1..*" ペア
チーム "0..1" -down-* "*" 参加者
ペア "0..1" -down-* "2..3" 参加者
参加者 "1" --* "*" 課題進捗ステータス
課題進捗ステータス "*" *-- "1" 課題
@enduml