@startuml

/'
  ユーザー
  クーロンジョブ
  ユーザー_ジョブ_リンク
 '/


entity "ユーザー" as users {
  + ユーザーID [PK]
  --
  ユーザー名
}

entity "クーロンジョブ" as cronjobs {
  + ジョブID [PK]
  --
  リマインド文面
}

/'
  "1-10"は1〜10で10レコードで持つ
  "1,5,10"は3レコード
  "*/2"は0,2,4,6,8,10,12,...,20,22のレコードを持つ
 '/
entity "クーロンスケジュール" as schedule {
  + ジョブID [PK]
  + スケジュールID [PK]
  --
  分
  時
  日
  月
  曜日
}

entity "ユーザージョブリンク" as user_job_links {
  + ユーザーID [PK]
  + ジョブID [PK]
}

/'
関係性
------   :1
----||   :1 and only 1
----o|   :0 or 1
-----{   :many
----|{   :1 or more
----o{   :0 or many

entityの位置
ri ...right
le ...left
do ...down
'/
users --ri-{ user_job_links
user_job_links }-ri-- cronjobs
cronjobs --do-{ schedule

@enduml
