@startuml
!theme aws-orange
skinparam PackageStyle rectangle

object 参加者 {
  参加者ID
  名前
  メールアドレス
  在籍ステータス
  課題リスト
}

object 課題 {
  課題ID
  進捗ステータス
}

object ペア {
  ペアID
  ペア名
  参加者リスト
}

object チーム {
  チームID
  チーム名
  ペアリスト
  参加者リスト
}

note right of 参加者 {
  - メールアドレスは重複しない
  - 在籍ステータスは[在籍, 休会, 退会]のいずれか
  - 在籍ステータスが"在籍"以外の場合、チーム, ペアには所属しない
}

note right of 課題 {
  - 進捗ステータスは[未着手, レビュー待ち, 完了]のいずれか
  - 進捗ステータスを変えられるのは課題の所有者のみ
  - 進捗ステータスが完了のものは[未着手, レビュー待ち]に戻せない
}

note right of ペア {
  - ペア名は英字のみ, 1文字
  - 参加者リストは2~3名, 同じチームの参加者のみ
}

note left of チーム {
  - チーム名は数字のみ, 3文字以下, 重複しない
  - 参加者リストは最低3名
}

チーム "1" -right-* "1..*" ペア
チーム "1" -right-* "3..*" 参加者
ペア "1" --* "2..3" 参加者
参加者 "1" -down-* "1..*" 課題

@enduml
